apiVersion: apps/v1
kind: Deployment
metadata:
  name: showenv-deployment
  labels:
    app: showenv
spec:
  replicas: 3
  selector:
    matchLabels:
      app: showenv
  template:
    metadata:
      labels:
        app: showenv
    spec:
      containers:
      - name: showenv
        image: proksch/showenv
        ports:
        - containerPort: 8080
        env:
          - name: MODEL_HOST
            valueFrom:
              configMapKeyRef:
                name: my-config
                key: host-name
          - name: DB_PWD
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: db.pwd
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: showenv
  ports:
    - port: 1234
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-ingress
spec:
  defaultBackend:
    service:
      name: my-service
      port:
        number: 1234
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
data:
  host-name: http://whatever
---
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
data:
  db.pwd: Zm9vYmFy
